apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: jvlrcnb0o-nodejs-gitops
  description: This is GitOps manifest for jvlrcnb0o-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=jvlrcnb0o-nodejs
    backstage.io/kubernetes-id: jvlrcnb0o-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: jvlrcnb0o-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:jvlrcnb0o-nodejs
