apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jvlrcnb0o-nodejs
  janus-idp.io/tekton: jvlrcnb0o-nodejs
  backstage.io/kubernetes-id: jvlrcnb0o-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jvlrcnb0o-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
